### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by alisonjo2786** [CommerceGov/DataCorps_WebSite#5] opened 2015-09-11 15:32 UTC
(numbers correspond with those in screenshot)

* [x] 1. Seal (probably the wrapping element) looks like it's jogged-down a little.
* [x] 2. Whitespace between navbar and main content -- and between menu icon and menu link text.
* [x] 3. Drop-down panel in right-hand menus is jogged-up a little (so it's overlapping with the navbar instead of sitting flush underneath).
* [x] ~~4. Search drop-down isn't tall enough, or the interior elements are shifted down -- one way or another, it runs out of space at the bottom of the search drop-down panel.~~ _I'm seeing that this is an issue on Commerce.gov -- it's not due to your styling._
* [x] 5. Gap between right-hand menu items and bottom of navbar.

![datacorps_navbar-issues1](https://cloud.githubusercontent.com/assets/2660348/9818683/cdb01a06-5877-11e5-8293-651bbed78017.png)

**Comment by alisonjo2786** [comment] 2015-09-14 20:20
@tyronegrandison FYI all of the items in this issue persist now that the site is on the c.gov server.

**Comment by SigmaMonstR** [comment] 2015-09-16 14:01
amazing what one line of code does. closing out. Check the test site on aws.

**Comment by alisonjo2786** [comment] 2015-09-21 20:53
Hey @SigmaMonstR -- one more! :)  In the Search drop-down, the font size of Person Finder and Advanced Search is off:

![datacorps_navbar_search-fonts 20150921](https://cloud.githubusercontent.com/assets/2660348/10004718/201960f2-6081-11e5-9cbb-4cce91b1a200.png)

**Comment by alisonjo2786** [comment] 2015-09-21 20:54
(in the future would you rather I create a new issue, or would you prefer I re-open like this?)

**Comment by SigmaMonstR** [comment] 2015-09-24 19:55
Size should be fine now in the most recent commit.

**Comment by tyronegrandison** [comment] 2015-09-24 20:07
@alisonjo2786 Re-opening the issue is same. 

Can you check that the size issue is no longer there and close this issue?

**Comment by alisonjo2786** [comment] 2015-09-24 20:33
Yes, as soon as we've pulled.  Thank you!

**Comment by tyronegrandison** [comment] 2015-09-24 23:34
Pull complete

**Closed by tyronegrandison** 2015-09-24 23:34 UTC

**Comment by alisonjo2786** [comment] 2015-09-25 01:02
Looks good, thanks!
​
